# Generated by Django 3.2.8 on 2021-10-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='info',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
