# Generated by Django 3.2.8 on 2021-10-27 20:55

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default=None, max_length=50)),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=500)),
                ('price', models.IntegerField(default=None)),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('highlight', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, size=None)),
                ('composition', models.CharField(default=None, max_length=50)),
                ('washing_instruction', models.CharField(default=None, max_length=50)),
                ('wearing', models.CharField(default=None, max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(related_name='products', to='category.Category')),
                ('owner', models.ManyToManyField(related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
