# Generated by Django 3.2.8 on 2021-10-21 14:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=300), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='highlight',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=50), size=None),
        ),
    ]
