# Generated by Django 3.2.8 on 2021-10-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='washing_instruction',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='wearing',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
